### ISSUE TITLE
ERROR while running on terminal

### ISSUE THREAD

**Issue by imranshaik012** [codeasashu/swagman#2]
getting error while running a project 

![image](https://user-images.githubusercontent.com/33627789/95688151-90f17a80-0c25-11eb-842a-b1e3d55f4e96.png)
 File "run.py", line 36, in <module>
    cli()

**Comment by codeasashu** [comment]
can you post the full error?

**Comment by imranshaik012** [comment]
Below is the code for an api with using POST method


@app.route('/convert', methods=['POST'])
def cli(format, ignore, postmanfile, outfile):
    try:
        postmanfile = ('./collection.json')
        converter = swagman.Converter(request.body.fileName)
        swagger_output = converter.convert(format) 
        return jsonify({
        'data': swagger_output
        })
        with open(outfile, 'w') as f:
            f.write(swagger_output)
            click.echo(click.style('Schema converted successfully!', fg='green'))
            f.close()
    except ValueError as e:
          return False
if __name__ == '__main__':
    app.run(debug=True)
    cli()



**I Run the Command**

python run.py collection.json openapi.yaml


till here its working fine it has created openapi file which is empty

On sending request with postman in the body i am passing input as filename  also i tried using string instead of file same error i am getting

![image](https://user-images.githubusercontent.com/33627789/95726254-4fe57e80-0c96-11eb-88a1-0904ca7ea194.png)

It throws an error on console

![image](https://user-images.githubusercontent.com/33627789/95726285-5e339a80-0c96-11eb-8878-da41c9c13ba5.png)

**Comment by Infosec-RKR** [comment]
@codeasashu @imranshaik012 

I do still get the same " TypeError"
python run.py MY.postman_collection.json swagger1.yaml

TypeError: 'pmrequest' object is not subscriptable

Traceback (most recent call last):
  File "run.py", line 32, in <module>
    cli()
  File "C:\Users\infosec\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 764, in __call__

**Comment by codeasashu** [comment]
@Infosec-RKR Sorry but I've renamed this project to openman. It contains a lot of bugfixes and have better mocking capabilities.

https://github.com/codeasashu/openman

Can you try that and see if it fixes the issue?
