### ISSUE TITLE
Missing required positional argument: 'data'

### ISSUE THREAD

**Issue by shuarey** [codeasashu/swagman#4]
I'm using swagman differently I think from your examples. Here is my command:

`C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts>swagman -f json -o swagger.json collection.postman_collection.json`

and here is the full error I got:
```
Traceback (most recent call last):
  File "c:\users\User\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\User\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\swagman.exe\__main__.py", line 7, in <module>
  File "c:\users\User\appdata\local\programs\python\python39\lib\site-packages\swagman.py", line 880, in main
    environment = CollectionContext.from_file(args.environment)
  File "c:\users\User\appdata\local\programs\python\python39\lib\site-packages\swagman.py", line 68, in from_file
    return cls()
TypeError: __init__() missing 1 required positional argument: 'data'
```

**Comment by codeasashu** [comment]
@shuarey  Sorry but I've renamed this project to openman. It contains a lot of bugfixes and have better mocking capabilities. Can you give it a try and see if it fixes the issue?

https://github.com/codeasashu/openman
